export const MUNICIPIOS_RJ = [
  "Rio de Janeiro",
  "Angra dos Reis",
  "Aperibé",
  "Araruama",
  "Areal",
  "Armação dos Búzios",
  "Arraial do Cabo",
  "Barra do Piraí",
  "Barra Mansa",
  "Belford Roxo",
  "Bom Jardim",
  "Bom Jesus do Itabapoana",
  "Cabo Frio",
  "Cachoeiras de Macacu",
  "Cambuci",
  "Campos dos Goytacazes",
  "Cantagalo",
  "Carapebus",
  "Cardoso Moreira",
  "Carmo",
  "Casimiro de Abreu",
  "Comendador Levy Gasparian",
  "Conceição de Macabu",
  "Cordeiro",
  "Duas Barras",
  "Duque de Caxias",
  "Engenheiro Paulo de Frontin",
  "Guapimirim",
  "Iguaba Grande",
  "Itaboraí",
  "Itaguaí",
  "Italva",
  "Itaocara",
  "Itaperuna",
  "Itatiaia",
  "Japeri",
  "Laje do Muriaé",
  "Macaé",
  "Macuco",
  "Magé",
  "Mangaratiba",
  "Maricá",
  "Mendes",
  "Mesquita",
  "Miguel Pereira",
  "Miracema",
  "Natividade",
  "Nilópolis",
  "Niterói",
  "Nova Friburgo",
  "Nova Iguaçu",
  "Paracambi",
  "Paraíba do Sul",
  "Paraty",
  "Paty do Alferes",
  "Petrópolis",
  "Pinheiral",
  "Piraí",
  "Porciúncula",
  "Porto Real",
  "Quatis",
  "Queimados",
  "Quissamã",
  "Resende",
  "Rio Bonito",
  "Rio Claro",
  "Rio das Flores",
  "Rio das Ostras",
  "Santa Maria Madalena",
  "Santo Antônio de Pádua",
  "São Fidélis",
  "São Francisco de Itabapoana",
  "São Gonçalo",
  "São João da Barra",
  "São João de Meriti",
  "São José de Ubá",
  "São José do Vale do Rio Preto",
  "São Pedro da Aldeia",
  "São Sebastião do Alto",
  "Sapucaia",
  "Saquarema",
  "Seropédica",
  "Silva Jardim",
  "Sumidouro",
  "Tanguá",
  "Teresópolis",
  "Trajano de Moraes",
  "Três Rios",
  "Valença",
  "Varre-Sai",
  "Vassouras",
  "Volta Redonda",
];

export const BAIRROS_RIO = [
  "Abolição",
  "Acari",
  "Água Santa",
  "Alto da Boa Vista",
  "Anchieta",
  "Andaraí",
  "Bancários",
  "Bangu",
  "Barra da Tijuca",
  "Barra de Guaratiba",
  "Benfica",
  "Bonsucesso",
  "Brás de Pina",
  "Cachambi",
  "Caju",
  "Caminho dos Deuses",
  "Campo dos Afonsos",
  "Campo Grande",
  "Cascadura",
  "Catete",
  "Catumbi",
  "Centro",
  "Cidade de Deus",
  "Cidade Nova",
  "Cidade Universitária",
  "Coelho Neto",
  "Colégio",
  "Complexo do Alemão",
  "Copacabana",
  "Cordovil",
  "Costa Barros",
  "Cosmos",
  "Cosme Velho",
  "Curicica",
  "Del Castilho",
  "Deodoro",
  "Encantado",
  "Engenheiro Leal",
  "Engenheiro Pedreira",
  "Engenho da Rainha",
  "Engenho de Dentro",
  "Engenho Novo",
  "Estácio",
  "Feira de São Cristóvão",
  "Flamengo",
  "Freguesia (Ilha)",
  "Freguesia (Jacarepaguá)",
  "Galeão",
  "Gamboa",
  "Gardênia Azul",
  "Glória",
  "Grajaú",
  "Grumari",
  "Guadalupe",
  "Guaratiba",
  "Higienópolis",
  "Honório Gurgel",
  "Humaitá",
  "Inhaúma",
  "Inhoaíba",
  "Ipanema",
  "Irajá",
  "Itanhangá",
  "Jacaré",
  "Jacarepaguá",
  "Jacarezinho",
  "Jardim América",
  "Jardim Botânico",
  "Jardim Guanabara",
  "Jardim Sulacap",
  "Joá",
  "Lagoa",
  "Laranjeiras",
  "Leme",
  "Lins de Vasconcelos",
  "Madureira",
  "Mangueira",
  "Manguinhos",
  "Maracanã",
  "Marechal Hermes",
  "Maré",
  "Méier",
  "Moneró",
  "Olaria",
  "Oswaldo Cruz",
  "Paciência",
  "Paquetá",
  "Parada de Lucas",
  "Pavuna",
  "Pedra de Guaratiba",
  "Penha",
  "Penha Circular",
  "Piedade",
  "Pilares",
  "Pitangueiras",
  "Portuguesa",
  "Praça da Bandeira",
  "Praça Seca",
  "Praia da Bandeira",
  "Quintino Bocaiúva",
  "Ramos",
  "Realengo",
  "Recreio dos Bandeirantes",
  "Riachuelo",
  "Ribeira",
  "Ricardo de Albuquerque",
  "Rio Comprido",
  "Rocha",
  "Rocha Miranda",
  "Rocinha",
  "Santa Cruz",
  "Santa Teresa",
  "Santíssimo",
  "Santo Cristo",
  "São Conrado",
  "São Cristóvão",
  "São Francisco Xavier",
  "Saúde",
  "Senador Camará",
  "Senador Vasconcelos",
  "Sepetiba",
  "Taquara",
  "Tauá",
  "Tijuca",
  "Todos os Santos",
  "Tomás Coelho",
  "Turiaçu",
  "Urca",
  "Vargem Grande",
  "Vargem Pequena",
  "Vargens",
  "Vasco da Gama",
  "Vigário Geral",
  "Vila Isabel",
  "Vila Kosmos",
  "Vila Militar",
  "Vila Valqueire",
  "Outro (não listado)",
];
